from enum import StrEnum


class ErrorCode(StrEnum):
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_CODE_EXISTS = "PROJECT_CODE_EXISTS"
    PROJECT_HAS_RELATED_DATA = "PROJECT_HAS_RELATED_DATA"
    SMART_INBOX_FILE_REQUIRED = "SMART_INBOX_FILE_REQUIRED"
    SMART_INBOX_NOT_FOUND = "SMART_INBOX_NOT_FOUND"
    IMPORT_BATCH_NOT_FOUND = "IMPORT_BATCH_NOT_FOUND"
    IMPORT_BATCH_HAS_ERRORS = "IMPORT_BATCH_HAS_ERRORS"
    IMPORT_BATCH_REPLACEMENT_REQUIRED = "IMPORT_BATCH_REPLACEMENT_REQUIRED"
    IMPORT_BATCH_ALREADY_PUBLISHED = "IMPORT_BATCH_ALREADY_PUBLISHED"
    UNSUPPORTED_EXCEL_FILE = "UNSUPPORTED_EXCEL_FILE"
    ISSUE_NOT_FOUND = "ISSUE_NOT_FOUND"
    INVALID_ISSUE_STATUS_TRANSITION = "INVALID_ISSUE_STATUS_TRANSITION"
    ISSUE_REVIEW_REQUIRED = "ISSUE_REVIEW_REQUIRED"
    INVALID_ISSUE_VALUE = "INVALID_ISSUE_VALUE"
