from enum import StrEnum


class ErrorCode(StrEnum):
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_CODE_EXISTS = "PROJECT_CODE_EXISTS"
    PROJECT_HAS_RELATED_DATA = "PROJECT_HAS_RELATED_DATA"
    SMART_INBOX_FILE_REQUIRED = "SMART_INBOX_FILE_REQUIRED"
